package jdbc25.statement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

//입력한 행의 자동 생성된 키값(일련번호) 가져오기
/*
 * CREATE TABLE BBS(
NO NUMBER PRIMARY KEY,
TITLE NVARCHAR2(50) NOT NULL,
USERNAME VARCHAR2(10) REFERENCES MEMBER(USERNAME),
POSTDATE DATE DEFAULT SYSDATE);
0C00REATE SEQUENCE SEQ_BBS NOCACHE NOCYCLE;
 * 
 * 하고옴
 */
public class InsertSQLAutoGeneratedkeys {

	//멤버변수
	private Connection conn;//지역변수 아니니까 접근지정자o
	private Statement stmt;
	//생성자
	public InsertSQLAutoGeneratedkeys() {
		
		try {
			//1]JDBC용 오라클 드라이버를 메모리에 로딩
			Class.forName("oracle.jdbc.OracleDriver");//외워라 그냥~
			//2]오라클에 연결시도:DriverManager의 getConnection()메소드로
			//이번엔 ip로!, ip는 컴퓨터주소임, naver.com 도메인은 다 기억함, ip기억못하니까 쓰는거, 도메인 대신 http://ip로도 naver접속됨
			conn=DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","kosmo","kosmo1234");//kosmo로 접속한다~
		} 
		catch (ClassNotFoundException e) {
			System.out.println("드라이버 클래스가 없어요. 드라이버 로딩 실패..");
		}
		catch (SQLException e) {
			System.out.println("데이터베이스 연결 실패");//getConnection 잡음
		}
	}////InsertSQL()
	//닫는 메소드 생성
	private void close() {
		try {
			if(stmt!=null) stmt.close();
			if(conn!=null) conn.close();
		}
		catch (SQLException e) {}
	}////close() 
	//Exec 메소드 생성
	private void execute() {
		
		try {
			//3]쿼리 실행하기 위한 Statement객체 생성. 연결된 Connection객체로...
			stmt=conn.createStatement();
			//4]Statement계열 객체로 쿼리 실행
			//쿼리문이 DELETE,UPDATE,INSERT일때는 int executeUpdate()-> 영향받은 행의 수 int반환
			//쿼리문이 SELECT일때는 ResultSet executeQuery()호출
			try {
				//int affected=stmt.executeUpdate("INSERT INTO MEMBER VALUES('PARK','1234','박길동',SYSDATE)");//영향받은 행의 수
				String sql="INSERT INTO BBS VALUES(SEQ_BBS.NEXTVAL,'제목1','KIM',SYSDATE)";
				//int affected=stmt.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);//입력 행의 생성된 키값 반환,근데 오라클은 시퀀스써서 안됨, 오라클은 그냥 영향받은 행의 수 나옴
				//int affected=stmt.executeUpdate(sql, new int[] {1});//오라클용. 1은 PK컬럼의 인덱스/ int형 배열 넣음, {1}하면 PK(키) 컬럼의 인덱스, 첫번쨰 컬럼 의미
				int affected=stmt.executeUpdate(sql, new String[] {"NO"});//오라클용. "NO"는 PK컬럼명
				System.out.println(affected+"행이 입력되었어요");
				//자동 생성된 키(숫자-PK)값 얻기
				ResultSet rs=stmt.getGeneratedKeys();//Resultset반환, 이걸로 키값을 가져옴, 위에 affected는 똑같이 영향받은 수 맞음
				if(rs.next()) {
					System.out.println("입력된 행의 자동생성된 키값:"+rs.getInt(1));//뭔지 몰라도 처음 실행시 키값 1이니까 인덱스 1나올것, NO가 실행할때마다 1,2,3..으로 나옴
				}
			}
			catch (SQLException e) {
				System.out.println("INSERT 쿼리문 실행오류:"+e.getMessage());
			}
		} 
		catch (SQLException e) {
			System.out.println("Statement객체 생성실패");
		}
		finally {
			close();
		}
	}////execute()
	
	public static void main(String[] args) {

		new InsertSQLAutoGeneratedkeys().execute();//객체생성하고 execute호출, 생성자 호출시 위의 오라클DB연결됨
		//InsertSQLAutoGeneratedkeys() isag=new InsertSQLAutoGeneratedkeys();
		//isag.execute();
		//두줄이랑 맨위 한줄 동일, 변수 필요없어서 맨위처럼한거임
		
		
	}////main
	

}////class
