/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-06-12 11:31:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Template_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/template/Top.jsp", Long.valueOf(1686569132092L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/0b4621b427.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /*점보트론 세로폭 및 마진바툼 줄이기*/\r\n");
      out.write("        .jumbotron{\r\n");
      out.write("            padding-top:1rem;\r\n");
      out.write("            padding-bottom:1rem;            \r\n");
      out.write("            margin-bottom: .5rem;\r\n");
      out.write("            \r\n");
      out.write("            border-top-left-radius:0;\r\n");
      out.write("            border-top-right-radius:0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("		html {\r\n");
      out.write("		  height: 100%;\r\n");
      out.write("		}\r\n");
      out.write("		body {\r\n");
      out.write("		  margin:0;\r\n");
      out.write("		  padding:0;\r\n");
      out.write("		  font-family: sans-serif;\r\n");
      out.write("		  background: linear-gradient(#141e30, #243b55);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box {\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  top: 50%;\r\n");
      out.write("		  left: 50%;\r\n");
      out.write("		  width: 400px;\r\n");
      out.write("		  padding: 40px;\r\n");
      out.write("		  transform: translate(-50%, -50%);\r\n");
      out.write("		  background: rgba(0,0,0,.5);\r\n");
      out.write("		  box-sizing: border-box;\r\n");
      out.write("		  box-shadow: 0 15px 25px rgba(0,0,0,.6);\r\n");
      out.write("		  border-radius: 10px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box h2 {\r\n");
      out.write("		  margin: 0 0 30px;\r\n");
      out.write("		  padding: 0;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  text-align: center;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box .user-box {\r\n");
      out.write("		  position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box .user-box input {\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		  padding: 10px 0;\r\n");
      out.write("		  font-size: 16px;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  margin-bottom: 30px;\r\n");
      out.write("		  border: none;\r\n");
      out.write("		  border-bottom: 1px solid #fff;\r\n");
      out.write("		  outline: none;\r\n");
      out.write("		  background: transparent;\r\n");
      out.write("		}\r\n");
      out.write("		.login-box .user-box label {\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  top:0;\r\n");
      out.write("		  left: 0;\r\n");
      out.write("		  padding: 10px 0;\r\n");
      out.write("		  font-size: 16px;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  pointer-events: none;\r\n");
      out.write("		  transition: .5s;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box .user-box input:focus ~ label,\r\n");
      out.write("		.login-box .user-box input:valid ~ label {\r\n");
      out.write("		  top: -20px;\r\n");
      out.write("		  left: 0;\r\n");
      out.write("		  color: #03e9f4;\r\n");
      out.write("		  font-size: 12px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box form a {\r\n");
      out.write("		  position: relative;\r\n");
      out.write("		  display: inline-block;\r\n");
      out.write("		  padding: 10px 20px;\r\n");
      out.write("		  color: #03e9f4;\r\n");
      out.write("		  font-size: 16px;\r\n");
      out.write("		  text-decoration: none;\r\n");
      out.write("		  text-transform: uppercase;\r\n");
      out.write("		  overflow: hidden;\r\n");
      out.write("		  transition: .5s;\r\n");
      out.write("		  margin-top: 40px;\r\n");
      out.write("		  letter-spacing: 4px\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a:hover {\r\n");
      out.write("		  background: #03e9f4;\r\n");
      out.write("		  color: #fff;\r\n");
      out.write("		  border-radius: 5px;\r\n");
      out.write("		  box-shadow: 0 0 5px #03e9f4,\r\n");
      out.write("		              0 0 25px #03e9f4,\r\n");
      out.write("		              0 0 50px #03e9f4,\r\n");
      out.write("		              0 0 100px #03e9f4;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a span {\r\n");
      out.write("		  position: absolute;\r\n");
      out.write("		  display: block;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a span:nth-child(1) {\r\n");
      out.write("		  top: 0;\r\n");
      out.write("		  left: -100%;\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		  height: 2px;\r\n");
      out.write("		  background: linear-gradient(90deg, transparent, #03e9f4);\r\n");
      out.write("		  animation: btn-anim1 1s linear infinite;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes btn-anim1 {\r\n");
      out.write("		  0% {\r\n");
      out.write("		    left: -100%;\r\n");
      out.write("		  }\r\n");
      out.write("		  50%,100% {\r\n");
      out.write("		    left: 100%;\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a span:nth-child(2) {\r\n");
      out.write("		  top: -100%;\r\n");
      out.write("		  right: 0;\r\n");
      out.write("		  width: 2px;\r\n");
      out.write("		  height: 100%;\r\n");
      out.write("		  background: linear-gradient(180deg, transparent, #03e9f4);\r\n");
      out.write("		  animation: btn-anim2 1s linear infinite;\r\n");
      out.write("		  animation-delay: .25s\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes btn-anim2 {\r\n");
      out.write("		  0% {\r\n");
      out.write("		    top: -100%;\r\n");
      out.write("		  }\r\n");
      out.write("		  50%,100% {\r\n");
      out.write("		    top: 100%;\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a span:nth-child(3) {\r\n");
      out.write("		  bottom: 0;\r\n");
      out.write("		  right: -100%;\r\n");
      out.write("		  width: 100%;\r\n");
      out.write("		  height: 2px;\r\n");
      out.write("		  background: linear-gradient(270deg, transparent, #03e9f4);\r\n");
      out.write("		  animation: btn-anim3 1s linear infinite;\r\n");
      out.write("		  animation-delay: .5s\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes btn-anim3 {\r\n");
      out.write("		  0% {\r\n");
      out.write("		    right: -100%;\r\n");
      out.write("		  }\r\n");
      out.write("		  50%,100% {\r\n");
      out.write("		    right: 100%;\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.login-box a span:nth-child(4) {\r\n");
      out.write("		  bottom: -100%;\r\n");
      out.write("		  left: 0;\r\n");
      out.write("		  width: 2px;\r\n");
      out.write("		  height: 100%;\r\n");
      out.write("		  background: linear-gradient(360deg, transparent, #03e9f4);\r\n");
      out.write("		  animation: btn-anim4 1s linear infinite;\r\n");
      out.write("		  animation-delay: .75s\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		@keyframes btn-anim4 {\r\n");
      out.write("		  0% {\r\n");
      out.write("		    bottom: -100%;\r\n");
      out.write("		  }\r\n");
      out.write("		  50%,100% {\r\n");
      out.write("		    bottom: 100%;\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 네비게이션 바  -->\r\n");
      out.write("	<!--상단 고정-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-sm bg-dark navbar-dark fixed-top\">   \r\n");
      out.write("      <!--Brand / Logo 표시-->      \r\n");
      out.write("      <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><i class=\"fa-solid fa-house-chimney\"></i></a>\r\n");
      out.write("      <!-- JSPProj 프로젝트 실행과 동일하게 링크 걸어줌, 아래 request.getContextPath()와 동일한 것, index.jsp로 이동하므로 자료실 나옴, 모델2방식 -->\r\n");
      out.write("      <!-- Navbar text-->\r\n");
      out.write("      <span class=\"navbar-text\">\r\n");
      out.write("        모두를 위한 플랫폼\r\n");
      out.write("      </span>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Toggler/collapsibe Button -->\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"collapse navbar-collapse justify-content-end\" id=\"collapsibleNavbar\">\r\n");
      out.write("       \r\n");
      out.write("        <!-- Links -->\r\n");
      out.write("        <ul class=\"navbar-nav mr-3\"><!--mr-3은 Navbar text와의 여백용-->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath() );
      out.write("/session06/Login.jsp\">로그인(세션) <i class=\"fa fa-user-o\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath() );
      out.write("/session06/Logout.jsp\">로그아웃(세션) <i class=\"fa fa-user-plus\"></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath() );
      out.write("/session06/LoginBasedToken.jsp\">로그인(토큰) <i class='fas fa-sign-in-alt'></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link active\" href=\"");
      out.print(request.getContextPath() );
      out.write("/session06/LogoutBasedToken.jsp\">로그아웃(토큰) <i class='fas fa-sign-out-alt'></i></a>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"#\">마이페이지</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"");
      out.print(request.getContextPath() );
      out.write("/bbs08/List.jsp\">게시판</a>\r\n");
      out.write("          </li>   \r\n");
      out.write("          <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link \" href=\"<c:url value=\"/DataRoom/List.kosmo\"/>\">자료실</a>\r\n");
      out.write("          </li>    \r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"login-box\">\r\n");
      out.write("	  <h2>MEDI-Q</h2>\r\n");
      out.write("	  <form>\r\n");
      out.write("	    <div class=\"user-box\">\r\n");
      out.write("	      <input type=\"text\" name=\"\" required=\"\">\r\n");
      out.write("	      <label>아이디</label>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"user-box\">\r\n");
      out.write("	      <input type=\"password\" name=\"\" required=\"\">\r\n");
      out.write("	      <label>비밀번호</label>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <a href=\"#\">\r\n");
      out.write("	      <span></span>\r\n");
      out.write("	      <span></span>\r\n");
      out.write("	      <span></span>\r\n");
      out.write("	      <span></span>\r\n");
      out.write("	      로그인\r\n");
      out.write("	    </a>\r\n");
      out.write("	  </form>\r\n");
      out.write("	</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/template/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
