
/* Drop Tables */

DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE ONEMEMO CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE COMMENTS
(
	LNO number NOT NULL,
	LINECOMMENT nvarchar2(50) NOT NULL,
	LPOSTDATE date DEFAULT SYSDATE,
	NO number NOT NULL,
	ID varchar2(10) NOT NULL,
	PRIMARY KEY (LNO)
);


CREATE TABLE MEMBER
(
	ID varchar2(10) NOT NULL,
	PWD varchar2(10) NOT NULL,
	NAME varchar2(20) NOT NULL,
	GENDER varchar2(10) NOT NULL,
	INTER varchar2(10) NOT NULL,
	GRADE varchar2(10) NOT NULL,
	SELF varchar2(50) NOT NULL,
	REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (ID)
);


CREATE TABLE ONEMEMO
(
	NO number NOT NULL,
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	POSTDATE date DEFAULT SYSDATE,
	ID varchar2(10) NOT NULL,
	PRIMARY KEY (NO)
);



/* Create Foreign Keys */

ALTER TABLE COMMENTS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE ONEMEMO
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (NO)
	REFERENCES ONEMEMO (NO)
;



